//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.13 at 03:55:24 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/suite/types/")
package localhost._8080.suite.types;
